import chessdotcom


def test_available_imports():
    assert hasattr(chessdotcom, "ChessDotComClient")
    assert hasattr(chessdotcom, "Client")
    assert hasattr(chessdotcom, "RateLimitHandler")

    assert hasattr(chessdotcom, "get_club_details")
    assert hasattr(chessdotcom, "get_club_matches")
    assert hasattr(chessdotcom, "get_club_members")
    assert hasattr(chessdotcom, "get_country_clubs")
    assert hasattr(chessdotcom, "get_country_details")
    assert hasattr(chessdotcom, "get_country_players")
    assert hasattr(chessdotcom, "get_current_daily_puzzle")
    assert hasattr(chessdotcom, "get_leaderboards")
    assert hasattr(chessdotcom, "get_player_clubs")
    assert hasattr(chessdotcom, "get_player_current_games")
    assert hasattr(chessdotcom, "get_player_current_games_to_move")
    assert hasattr(chessdotcom, "get_player_game_archives")
    assert hasattr(chessdotcom, "get_player_games_by_month")
    assert hasattr(chessdotcom, "get_player_games_by_month_pgn")
    assert hasattr(chessdotcom, "get_player_profile")
    assert hasattr(chessdotcom, "get_player_stats")
    assert hasattr(chessdotcom, "get_player_team_matches")
    assert hasattr(chessdotcom, "get_player_tournaments")
    assert hasattr(chessdotcom, "get_random_daily_puzzle")
    assert hasattr(chessdotcom, "get_streamers")
    assert hasattr(chessdotcom, "get_team_match")
    assert hasattr(chessdotcom, "get_team_match_board")
    assert hasattr(chessdotcom, "get_team_match_live")
    assert hasattr(chessdotcom, "get_team_match_live_board")
    assert hasattr(chessdotcom, "get_titled_players")
    assert hasattr(chessdotcom, "get_tournament_details")
    assert hasattr(chessdotcom, "get_tournament_round")
    assert hasattr(chessdotcom, "get_tournament_round_group_details")

    assert hasattr(chessdotcom, "ChessDotComClientError")
    assert hasattr(chessdotcom, "ChessDotComError")
    assert hasattr(chessdotcom, "ChessDotComResponse")
